# Generated by Django 3.2.4 on 2021-07-22 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Garments', '0002_trousers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formalshirt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Garments.formalshirt')),
            ],
        ),
    ]
