# Generated by Django 3.2.4 on 2021-07-23 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Garments', '0003_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='tr',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Garments.trousers'),
        ),
        migrations.AlterField(
            model_name='trousers',
            name='name',
            field=models.CharField(default='', max_length=85),
        ),
        migrations.AlterField(
            model_name='trousers',
            name='photo',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
    ]
