# Generated by Django 3.2.4 on 2021-07-24 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Garments', '0006_auto_20210724_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formalshirt',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='formalshirt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Garments.formalshirt'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='tr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Garments.trousers'),
        ),
        migrations.AlterField(
            model_name='trousers',
            name='name',
            field=models.CharField(blank=True, max_length=85),
        ),
        migrations.AlterField(
            model_name='trousers',
            name='photo',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
