# Generated by Django 3.2.4 on 2021-07-24 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Garments', '0008_alter_orders_tr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='formalshirt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Garments.formalshirt'),
        ),
    ]
