# Generated by Django 3.2.4 on 2021-07-24 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Garments', '0009_alter_orders_formalshirt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='formalshirt',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='Garments.formalshirt'),
        ),
    ]
