# Generated by Django 3.2.4 on 2021-07-24 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Garments', '0010_alter_orders_formalshirt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='tr',
            new_name='trousers',
        ),
        migrations.AlterField(
            model_name='formalshirt',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='formalshirt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Garments.formalshirt'),
        ),
        migrations.AlterField(
            model_name='trousers',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
