# Generated by Django 3.2.4 on 2021-07-24 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Garments', '0013_auto_20210724_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='formalshirt',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='Garments.formalshirt'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='trousers',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='Garments.trousers'),
        ),
    ]
