# Generated by Django 3.2.4 on 2021-07-24 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Garments', '0014_auto_20210724_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formalshirt', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='Garments.formalshirt')),
            ],
        ),
        migrations.CreateModel(
            name='Order2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trousers', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='Garments.trousers')),
            ],
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
