# Generated by Django 3.2.4 on 2021-07-24 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Garments', '0015_auto_20210724_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order1',
            name='formalshirt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Garments.formalshirt'),
        ),
        migrations.AlterField(
            model_name='order2',
            name='trousers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Garments.trousers'),
        ),
    ]
