# Generated by Django 3.2.4 on 2021-07-24 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Garments', '0016_auto_20210724_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formalshirt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Garments.formalshirt')),
                ('trousers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Garments.trousers')),
            ],
        ),
        migrations.RemoveField(
            model_name='order2',
            name='trousers',
        ),
        migrations.DeleteModel(
            name='Order1',
        ),
        migrations.DeleteModel(
            name='Order2',
        ),
    ]
